FROM ogomez/arm32v7-alpine

EXPOSE 3306

WORKDIR /app
VOLUME /app

RUN apk add --update mysql mysql-client && rm -f /var/cache/apk/*

RUN mkdir /run/mysqld/
RUN mkfifo /run/mysqld/mysqld.sock
RUN chown -R root /run/mysqld/

COPY startup.sh /startup.sh
COPY my.cnf /etc/mysql/my.cnf


CMD ["/startup.sh"]